const movies = {
  killBill: {
    adult: false,
    backdrop_path: '/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg',
    genre_ids: [28, 80],
    id: 24,
    original_language: 'en',
    original_title: 'Kill Bill: Vol. 1',
    overview:
      'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.',
    popularity: 39.675,
    poster_path: '/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg',
    release_date: '10-10-2003',
    title: 'Kill Bill: Vol. 1',
    video: false,
    vote_average: 8,
    vote_count: 14737,
  },
  pulpFiction: {
    adult: false,
    backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    genre_ids: [53, 80],
    id: 680,
    original_language: 'en',
    original_title: 'Pulp Fiction',
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 65.772,
    poster_path: '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
    release_date: '09-10-1994',
    title: 'Pulp Fiction',
    video: false,
    vote_average: 8.5,
    vote_count: 23371,
  },
  holes: {
    adult: false,
    backdrop_path: '/4h4u0qZvaxdtbLuhmMqVAVbd59K.jpg',
    genre_ids: [12, 10751, 18, 35],
    id: 8326,
    original_language: 'en',
    original_title: 'Holes',
    overview:
      "Stanley's family is cursed with bad luck. Unfairly sentenced to months of detention at Camp Green Lake, he and his campmates are forced by the warden to dig holes in order to build character. What they don't know is that they are digging holes in order to search for a lost treasure hidden somewhere in the camp.",
    popularity: 15.547,
    poster_path: '/w3KHhv3Lb42lqdd95mAxYwM4AcF.jpg',
    release_date: '04-18-2003',
    title: 'Holes',
    video: false,
    vote_average: 6.8,
    vote_count: 1086,
  },
  schoolOfRock: {
    adult: false,
    backdrop_path: '/pM1CnP0ZN2VxmrTAbBZOS3PNoNE.jpg',
    genre_ids: [35, 10402, 10751],
    id: 1584,
    original_language: 'en',
    original_title: 'School of Rock',
    overview:
      "Fired from his band and hard up for cash, guitarist and vocalist Dewey Finn finagles his way into a job as a fifth-grade substitute teacher at a private school, where he secretly begins teaching his students the finer points of rock 'n' roll. The school's hard-nosed principal is rightly suspicious of Finn's activities. But Finn's roommate remains in the dark about what he's doing.",
    popularity: 24.048,
    poster_path: '/zXLXaepIBvFVLU25DH3wv4IPSbe.jpg',
    release_date: '10-03-2003',
    title: 'School of Rock',
    video: false,
    vote_average: 7.1,
    vote_count: 4678,
  },
  fullMetalJacket: {
    adult: false,
    backdrop_path: '/yozBWKbyeXtPGN75PlHurOaVvEz.jpg',
    genre_ids: [18, 10752],
    id: 600,
    original_language: 'en',
    original_title: 'Full Metal Jacket',
    overview:
      'A pragmatic U.S. Marine observes the dehumanizing effects the U.S.-Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.',
    popularity: 32.926,
    poster_path: '/kMKyx1k8hWWscYFnPbnxxN4Eqo4.jpg',
    release_date: '06-26-1987',
    title: 'Full Metal Jacket',
    video: false,
    vote_average: 8.1,
    vote_count: 8605,
  },
  backToTheFuture: {
    adult: false,
    backdrop_path: '/fq3wyOs1RHyz2yfzsb4sck7aWRG.jpg',
    genre_ids: [12, 35, 878, 10751],
    id: 105,
    original_language: 'en',
    original_title: 'Back to the Future',
    overview:
      "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
    popularity: 58.333,
    poster_path: '/7lyBcpYB0Qt8gYhXYaEZUNlNQAv.jpg',
    release_date: '07-03-1985',
    title: 'Back to the Future',
    video: false,
    vote_average: 8.3,
    vote_count: 16665,
  },
  photoLink: 'image.tmdb.org/t/p/w300/',
};

export default movies;
